preset: laravel

enabled:
  - align_double_arrow
  - align_equals
  - length_ordered_imports
  - method_chaining_indentation

disabled:
  - self_accessor
  - short_list_syntax
  - alpha_ordered_imports
  - single_class_element_per_statement
